FROM node:20-alpine

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./pnpm-lock.yaml  ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml  ./pnpm-workspace.yaml

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/http-server ./apps/http-server
RUN npm install -g pnpm
RUN pnpm install
RUN npm run db:generate

EXPOSE 3001

CMD ["npm", "run", "start:backend"]